#---------- SYSTEM PATHs ----------
#INPUT_DATA_PATH = '/home/mdanaila/data/research_collection/input_test/'
#OUT_BCP_PATH = '/home/mdanaila/data/research_collection/bcp_out_test/'
INPUT_DATA_PATH = '/home/mdanaila/data/research_collection/input/'
OUT_BCP_PATH = '/home/mdanaila/data/research_collection/bcp_out/'
PATH_TO_CKONSORG_DATA = '/home/bibliometric/data/research_collection/ckonsorg/'

#---------- TABLEs NAME ----------
MASTER_TABLE = "RCMasterTable"
LEITZHAL_TABLE = "RCLeitzahl"
AUTHORSHIP_TABLE = "RCAuthorship"
PUBLICATION_TABLE = "RCPublication"
CKONSORG_TABLE = "RCckonsorg"

#---------- TABLEs SUBSETs ----------
CONTRIBUTOR_LABELS_SET = set([
	"handle_id",
	"rc_item_id",
    "dc_contributor_author",
    "dc_contributor_editor",
    "dc_contributor_supervisor",
    "dc_contributor_other",
    "dc_contributor_producer",
    "dc_contributor_researcher",
    "dc_contributor_contactPerson",
    "dc_contributor_dataCollector",
    "dc_contributor_projectMember",
    "dc_contributor_projectManager",
    "dc_contributor_projectLeader",
    "dc_contributor_rightsHolder"
])

#---------- TABLEs COLUMNs ----------
# 	'DEPT' is not present
CKONSORG_COLUMNS = [
	'perdat', 
	'lz90', 'na90',
	'lz80', 'na80', 
	'lz70', 'na70', 
	'lz60', 'na60', 
	'lz50', 'na50', 
	'lz40','na40', 
	'lz30', 'na30', 
	'lz20', 'na20', 
	'typneu', 
	'typname',
	'vondat', 
	'bisdat',
	'd_dept',
	'dept'
]

AUTHORSHIP_COLUMNS = [
    "handle_id", 
	"rc_id", 
	"full_name", 
	"type"
]

PUBLICATION_COLUMNS = [
	"handle_id",
    "rc_item_id",
    "dc_type",
	"ethz_eth",
    "ethz_leitzahl",
    "ethz_leitzahl_certified",
    "dc_title",
    "dc_date_issued",
	"rc_year",
    "dc_identifier_uri",
    "ethz_source",
	"dc_identifier_doi",
	"dc_identifier_other"
]

PUBLICATION_COLUMNS_EXT = [
	"handle_id",
    "rc_item_id",
    "dc_type",
	"ethz_eth",
    "ethz_leitzahl",
    "ethz_leitzahl_certified",
    "dc_title",
    "dc_date_issued",
	"rc_year",
    "dc_identifier_uri",
    "ethz_source",
	"dc_identifier_doi",
	"dc_identifier_other",
	"pub_lz"
]

LEITZAHL_COLUMNS = [
	"handle_id", 
	"rc_item_id", 
	"ou_code",
	"ou_name", 
	"is_leaf", 
	"is_certified"
]

LEITZAHL_COLUMNS_EXT = [
	"handle_id", 
	"rc_item_id", 
	"ou_code",
	"ou_name", 
	"is_leaf", 
	"is_certified",
	"lz_lv_match"
]

LEITZAHL_COLUMNS_TYPED = [
	"handle_id UNIQUE INT NOT NULL", 
	"rc_item_id UNIQUE INT NOT NULL", 
	"ou_code VARCHAR(8) NULL",
	"ou_name VARCHAR(255) NULL",
	"is_leaf CHAR(1) NULL", 
	"is_certified CHAR(1) NULL"
]

ALL_COLUMNS = [
	'dc_contributor_author',
 'dc_contributor_supervisor',
 'dc_date_accessioned',
 'dc_date_available',
 'dc_date_issued',
 'dc_format',
 'dc_identifier_doi',
 'dc_identifier_uri',
 'dc_language_iso',
 'dc_publisher',
 'dc_rights_license',
 'dc_rights_uri',
 'dc_subject',
 'dc_title',
 'dc_type',
 'ethz_availability',
 'ethz_code_ddc',
 'ethz_date_deposited',
 'ethz_ecolpid',
 'ethz_eth',
 'ethz_identifier_diss',
 'ethz_identifier_importid',
 'ethz_identifier_nebis',
 'ethz_notes',
 'ethz_publication_place',
 'ethz_publication_status',
 'ethz_rosetta_installdate',
 'ethz_rosetta_lastupdated',
 'ethz_rosetta_versionexported',
 'ethz_size',
 'ethz_source',
 'rc_item_id',
 'ethz_journal_title',
 'ethz_title_subtitle',
 'dc_title_alternative',
 'ethz_journal_volume',
 'ethz_rosetta_exportrequired',
 'ethz_relation_haspart',
 'ethz_relation_isoriginalformof',
 'dc_identifier_issn',
 'ethz_leitzahl',
 'ethz_leitzahl_certified',
 'ethz_leitzahlidentifiers',
 'ethz_leitzahlidentifiers_certified',
 'ethz_relation_isidenticalto',
 'ethz_relation_isvariantformof',
 'ethz_relation_ispartof',
 'dc_contributor_editor',
 'dc_identifier_other',
 'ethz_journal_abbreviated',
 'ethz_journal_issue',
 'ethz_pages_end',
 'ethz_pages_start',
 'ethz_relation_continues',
 'ethz_relation_iscontinuedby',
 'ethz_ecitpid',
 'dc_description_abstract',
 'ethz_book_title',
 'ethz_event',
 'ethz_event_date',
 'ethz_event_location',
 'dc_identifier_olduri',
 'ethz_version_deposit',
 'dc_identifier_isbn',
 'dc_date_published',
 'ethz_version_edition',
 'ethz_relation_cites',
 'ethz_identifier_scopus',
 'ethz_relation_issupplementedby',
 'dc_contributor_projectleader',
 'ethz_date_retentionend',
 'ethz_date_retentionenddate',
 'ethz_relation_issupplementto',
 'ethz_tag',
 'ethz_identifier_orcidworkcode',
 'ethz_relation_ispreviousversionof',
 'ethz_relation_isnewversionof',
 'ethz_identifier_wos',
 'ethz_date_embargoend',
 'ethz_identifier_url',
 'dc_relation_isnodouble',
 'ethz_relation_compiles',
 'ethz_relation_iscompiledby',
 'ethz_relation_iscitedby',
 'ethz_relation_references',
 'ethz_relation_isreferencedby',
 'ethz_identifier_internal',
 'ethz_code_jel',
 'ethz_version',
 'ethz_identifier_patent',
 'dc_contributor_contactperson',
 'dc_contributor_datacollector',
 'ethz_relation_isdocumentedby',
 'ethz_grant',
 'ethz_grant_agreementno',
 'ethz_grant_funderdoi',
 'ethz_grant_fundername',
 'ethz_grant_program',
 'ethz_relation_documents',
 'dc_contributor',
 'ethz_identifier_arxiv',
 'ethz_identifier_pubmed',
 'ethz_description_methods',
 'dc_contributor_other',
 'ethz_date_collected',
 'dc_relation_isreplacedbydouble',
 'ethz_relation_issourceof',
 'dc_contributor_researchgroup',
 'ethz_geolocation_placename',
 'ethz_geolocation_pointlat',
 'ethz_geolocation_pointlong',
 'ethz_identifier_urn',
 'ethz_relation_reviews',
 'dc_date_created',
 'ethz_relation_isderivedfrom',
 'dc_contributor_projectmanager',
 'dc_contributor_projectmember',
 'ethz_relation_isreviewedby',
 'ethz_openbis_error',
 'ethz_repository',
 'dc_identifier_wos',
 'dc_relation_ispartof',
 'ethz_description_software',
 'dc_contributor_producer',
 'dc_contributor_relatedperson',
 'dc_contributor_researcher',
 'dc_contributor_rightsholder',
 'dc_language',
 'dc_date_updated',
 'ethz_identifier_openbis',
 'ethz_identifier_openbisapiurl',
 'ethz_doipreview',
 'ethz_libdrive_url',
 'ethz_date_openbisupload',
 'handle_id'
]

ALL_COLUMNS_SORTED = ['dc_contributor',
 'dc_contributor_author',
 'dc_contributor_contactperson',
 'dc_contributor_datacollector',
 'dc_contributor_editor',
 'dc_contributor_other',
 'dc_contributor_producer',
 'dc_contributor_projectleader',
 'dc_contributor_projectmanager',
 'dc_contributor_projectmember',
 'dc_contributor_relatedperson',
 'dc_contributor_researcher',
 'dc_contributor_researchgroup',
 'dc_contributor_rightsholder',
 'dc_contributor_supervisor',
 'dc_date_accessioned',
 'dc_date_available',
 'dc_date_created',
 'dc_date_issued',
 'dc_date_published',
 'dc_date_updated',
 'dc_description_abstract',
 'dc_format',
 'dc_identifier_doi',
 'dc_identifier_isbn',
 'dc_identifier_issn',
 'dc_identifier_olduri',
 'dc_identifier_other',
 'dc_identifier_uri',
 'dc_identifier_wos',
 'dc_language',
 'dc_language_iso',
 'dc_publisher',
 'dc_relation_isnodouble',
 'dc_relation_ispartof',
 'dc_relation_isreplacedbydouble',
 'dc_rights_license',
 'dc_rights_uri',
 'dc_subject',
 'dc_title',
 'dc_title_alternative',
 'dc_type',
 'ethz_availability',
 'ethz_book_title',
 'ethz_code_ddc',
 'ethz_code_jel',
 'ethz_date_collected',
 'ethz_date_deposited',
 'ethz_date_embargoend',
 'ethz_date_openbisupload',
 'ethz_date_retentionend',
 'ethz_date_retentionenddate',
 'ethz_description_methods',
 'ethz_description_software',
 'ethz_doipreview',
 'ethz_ecitpid',
 'ethz_ecolpid',
 'ethz_eth',
 'ethz_event',
 'ethz_event_date',
 'ethz_event_location',
 'ethz_geolocation_placename',
 'ethz_geolocation_pointlat',
 'ethz_geolocation_pointlong',
 'ethz_grant',
 'ethz_grant_agreementno',
 'ethz_grant_funderdoi',
 'ethz_grant_fundername',
 'ethz_grant_program',
 'ethz_identifier_arxiv',
 'ethz_identifier_diss',
 'ethz_identifier_importid',
 'ethz_identifier_internal',
 'ethz_identifier_nebis',
 'ethz_identifier_openbis',
 'ethz_identifier_openbisapiurl',
 'ethz_identifier_orcidworkcode',
 'ethz_identifier_patent',
 'ethz_identifier_pubmed',
 'ethz_identifier_scopus',
 'ethz_identifier_url',
 'ethz_identifier_urn',
 'ethz_identifier_wos',
 'ethz_journal_abbreviated',
 'ethz_journal_issue',
 'ethz_journal_title',
 'ethz_journal_volume',
 'ethz_leitzahl',
 'ethz_leitzahl_certified',
 'ethz_leitzahlidentifiers',
 'ethz_leitzahlidentifiers_certified',
 'ethz_libdrive_url',
 'ethz_notes',
 'ethz_openbis_error',
 'ethz_pages_end',
 'ethz_pages_start',
 'ethz_publication_place',
 'ethz_publication_status',
 'ethz_relation_cites',
 'ethz_relation_compiles',
 'ethz_relation_continues',
 'ethz_relation_documents',
 'ethz_relation_haspart',
 'ethz_relation_iscitedby',
 'ethz_relation_iscompiledby',
 'ethz_relation_iscontinuedby',
 'ethz_relation_isderivedfrom',
 'ethz_relation_isdocumentedby',
 'ethz_relation_isidenticalto',
 'ethz_relation_isnewversionof',
 'ethz_relation_isoriginalformof',
 'ethz_relation_ispartof',
 'ethz_relation_ispreviousversionof',
 'ethz_relation_isreferencedby',
 'ethz_relation_isreviewedby',
 'ethz_relation_issourceof',
 'ethz_relation_issupplementedby',
 'ethz_relation_issupplementto',
 'ethz_relation_isvariantformof',
 'ethz_relation_references',
 'ethz_relation_reviews',
 'ethz_repository',
 'ethz_rosetta_exportrequired',
 'ethz_rosetta_installdate',
 'ethz_rosetta_lastupdated',
 'ethz_rosetta_versionexported',
 'ethz_size',
 'ethz_source',
 'ethz_tag',
 'ethz_title_subtitle',
 'ethz_version',
 'ethz_version_deposit',
 'ethz_version_edition',
 'handle_id',
 'rc_item_id'
]