version: '3'

volumes:
  bibliodb_volume:


services:

  bibliodb:
    image: postgres:alpine
    restart: always
    user: postgres:postgres
    volumes:
      - bibliodb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ethz_biblio
      - POSTGRES_DB=testbiblio
    ports:
      - "0.0.0.0:5433:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ethz_biblio
      - POSTGRES_DB=biblio
      - POSTGRES_HOST=bibliodb
    ports:
      - "9080:8080"
