"""wos

Revision ID: 7f9017e034e3
Revises: e97475514a35
Create Date: 2023-05-22 15:21:51.030762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f9017e034e3'
down_revision = 'e97475514a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NotLinkedWoSCitation',
    sa.Column('citing_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cited_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('citing_id', 'cited_id', 'uid')
    )
    op.create_table('WoSAffiliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_organizations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WoSAffiliation_organization'), 'WoSAffiliation', ['organization'], unique=False)
    op.create_table('WoSAuthor',
    sa.Column('wos_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('given_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_suffix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('e_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orcid_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('r_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('wos_standard')
    )
    op.create_table('WoSGrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_agency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grant_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WoSSource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abbrev', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_abbrev', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abbrev_iso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abbrev_11', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abbrev_29', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WoSSource_issn'), 'WoSSource', ['issn'], unique=False)
    op.create_index(op.f('ix_WoSSource_name'), 'WoSSource', ['name'], unique=False)
    op.create_table('WoSPublication',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_first', sa.Integer(), nullable=True),
    sa.Column('page_last', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_month', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subheadings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subjects', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('fund_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['WoSGrant.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['WoSSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WoSPublication_doi'), 'WoSPublication', ['doi'], unique=False)
    op.create_table('WoSAuthorship',
    sa.Column('publication_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['WoSAffiliation.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['WoSAuthor.wos_standard'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['WoSPublication.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'author_id', 'affiliation_id')
    )
    op.create_table('WoSCitation',
    sa.Column('citing_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cited_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cited_id'], ['WoSPublication.id'], ),
    sa.ForeignKeyConstraint(['citing_id'], ['WoSPublication.id'], ),
    sa.PrimaryKeyConstraint('citing_id', 'cited_id')
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WoSCitation')
    op.drop_table('WoSAuthorship')
    op.drop_index(op.f('ix_WoSPublication_doi'), table_name='WoSPublication')
    op.drop_table('WoSPublication')
    op.drop_index(op.f('ix_WoSSource_name'), table_name='WoSSource')
    op.drop_index(op.f('ix_WoSSource_issn'), table_name='WoSSource')
    op.drop_table('WoSSource')
    op.drop_table('WoSGrant')
    op.drop_table('WoSAuthor')
    op.drop_index(op.f('ix_WoSAffiliation_organization'), table_name='WoSAffiliation')
    op.drop_table('WoSAffiliation')
    op.drop_table('NotLinkedWoSCitation')
    # ### end Alembic commands ###
